// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using One_Pass_Fitness.Data;

#nullable disable

namespace One_Pass_Fitness.Migrations
{
    [DbContext(typeof(OnePassFitnessContext))]
    [Migration("20260427153233_LinkUsersToRolesDirectly")]
    partial class LinkUsersToRolesDirectly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("One_Pass_Fitness.Models.Classes", b =>
                {
                    b.Property<int>("ClassesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassesId"));

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Endtime")
                        .HasColumnType("time");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Starttime")
                        .HasColumnType("time");

                    b.HasKey("ClassesId");

                    b.HasIndex("RoleId");

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Membership", b =>
                {
                    b.Property<int>("Membershipid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Membershipid"));

                    b.Property<DateOnly>("Enddate")
                        .HasColumnType("date");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Roleid")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Startdate")
                        .HasColumnType("date");

                    b.HasKey("Membershipid");

                    b.HasIndex("Roleid");

                    b.ToTable("Membership", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Personalinfo", b =>
                {
                    b.Property<int>("Personalinfoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Personalinfoid"));

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Personalinfoid");

                    b.ToTable("Personalinfo", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Roles", b =>
                {
                    b.Property<int>("Rolesid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rolesid"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rolesid");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Users", b =>
                {
                    b.Property<int>("Usersid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Usersid"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Personid")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Usersid");

                    b.HasIndex("Personid");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Classes", b =>
                {
                    b.HasOne("One_Pass_Fitness.Models.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Membership", b =>
                {
                    b.HasOne("One_Pass_Fitness.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("Roleid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Users", b =>
                {
                    b.HasOne("One_Pass_Fitness.Models.Personalinfo", "Person")
                        .WithMany()
                        .HasForeignKey("Personid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("One_Pass_Fitness.Models.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
