// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using One_Pass_Fitness.Data;

#nullable disable

namespace One_Pass_Fitness.Migrations
{
    [DbContext(typeof(OnePassFitnessContext))]
    [Migration("20260412105739_restructure")]
    partial class restructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("One_Pass_Fitness.Models.BookingClasses", b =>
                {
                    b.Property<int>("BookingClassesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingClassesId"));

                    b.Property<string>("Attendancestatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Bookingdate")
                        .HasColumnType("date");

                    b.Property<int>("Classid")
                        .HasColumnType("int");

                    b.Property<int>("Memberid")
                        .HasColumnType("int");

                    b.HasKey("BookingClassesId");

                    b.HasIndex("Classid");

                    b.HasIndex("Memberid");

                    b.ToTable("BookingClasses", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Classes", b =>
                {
                    b.Property<int>("ClassesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassesId"));

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Endtime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("Starttime")
                        .HasColumnType("time");

                    b.Property<int>("Trainerid")
                        .HasColumnType("int");

                    b.HasKey("ClassesId");

                    b.HasIndex("Trainerid");

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Manager", b =>
                {
                    b.Property<int>("Managerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Managerid"));

                    b.Property<int>("Personid")
                        .HasColumnType("int");

                    b.HasKey("Managerid");

                    b.HasIndex("Personid");

                    b.ToTable("Manager", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Member", b =>
                {
                    b.Property<int>("Memberid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Memberid"));

                    b.Property<DateOnly>("Datejoined")
                        .HasColumnType("date");

                    b.Property<int>("Personid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Memberid");

                    b.HasIndex("Personid");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Membership", b =>
                {
                    b.Property<int>("Membershipid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Membershipid"));

                    b.Property<DateOnly>("Enddate")
                        .HasColumnType("date");

                    b.Property<int>("Memberid")
                        .HasColumnType("int");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Startdate")
                        .HasColumnType("date");

                    b.HasKey("Membershipid");

                    b.HasIndex("Memberid");

                    b.ToTable("Membership", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Personalinfo", b =>
                {
                    b.Property<int>("Personalinfoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Personalinfoid"));

                    b.Property<DateOnly>("DOB")
                        .HasMaxLength(100)
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Personalinfoid");

                    b.ToTable("Personalinfo", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Trainers", b =>
                {
                    b.Property<int>("Trainersid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trainersid"));

                    b.Property<DateOnly>("Datehired")
                        .HasColumnType("date");

                    b.Property<int>("Personid")
                        .HasColumnType("int");

                    b.Property<string>("Trainedfield")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Trainersid");

                    b.HasIndex("Personid");

                    b.ToTable("Trainers", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.BookingClasses", b =>
                {
                    b.HasOne("One_Pass_Fitness.Models.Classes", "Class")
                        .WithMany("Bookings")
                        .HasForeignKey("Classid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("One_Pass_Fitness.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("Memberid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Classes", b =>
                {
                    b.HasOne("One_Pass_Fitness.Models.Trainers", "Trainer")
                        .WithMany("Classes")
                        .HasForeignKey("Trainerid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Manager", b =>
                {
                    b.HasOne("One_Pass_Fitness.Models.Personalinfo", "Person")
                        .WithMany("Managers")
                        .HasForeignKey("Personid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Member", b =>
                {
                    b.HasOne("One_Pass_Fitness.Models.Personalinfo", "Person")
                        .WithMany("Members")
                        .HasForeignKey("Personid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Membership", b =>
                {
                    b.HasOne("One_Pass_Fitness.Models.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("Memberid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Trainers", b =>
                {
                    b.HasOne("One_Pass_Fitness.Models.Personalinfo", "Person")
                        .WithMany("Trainers")
                        .HasForeignKey("Personid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Classes", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Member", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Personalinfo", b =>
                {
                    b.Navigation("Managers");

                    b.Navigation("Members");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Trainers", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
