// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using One_Pass_Fitness.Data;

#nullable disable

namespace One_Pass_Fitness.Migrations
{
    [DbContext(typeof(OnePassFitnessContext))]
    [Migration("20260329111304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("One_Pass_Fitness.Models.Admin", b =>
                {
                    b.Property<int>("Adminid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Adminid"));

                    b.Property<int>("Personid")
                        .HasColumnType("int");

                    b.HasKey("Adminid");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.BookingClasses", b =>
                {
                    b.Property<int>("BookingClassesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingClassesId"));

                    b.Property<string>("Attendancestatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Bookingdate")
                        .HasColumnType("date");

                    b.Property<int>("Classid")
                        .HasColumnType("int");

                    b.Property<int>("Memberid")
                        .HasColumnType("int");

                    b.HasKey("BookingClassesId");

                    b.ToTable("BookingClasses", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Classes", b =>
                {
                    b.Property<int>("ClassesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassesId"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Endtime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("Starttime")
                        .HasColumnType("time");

                    b.Property<int>("Trainerid")
                        .HasColumnType("int");

                    b.HasKey("ClassesId");

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Member", b =>
                {
                    b.Property<int>("Memberid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Memberid"));

                    b.Property<DateOnly>("Datejoined")
                        .HasColumnType("date");

                    b.Property<int>("Personid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Memberid");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.MembershipInfo", b =>
                {
                    b.Property<int>("MembershipInfoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipInfoid"));

                    b.Property<DateOnly>("Enddate")
                        .HasColumnType("date");

                    b.Property<int>("Memberid")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Startdate")
                        .HasColumnType("date");

                    b.HasKey("MembershipInfoid");

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Personalinfo", b =>
                {
                    b.Property<int>("Personalinfoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Personalinfoid"));

                    b.Property<DateOnly>("DOB")
                        .HasMaxLength(100)
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Personalinfoid");

                    b.ToTable("Personalinfo", (string)null);
                });

            modelBuilder.Entity("One_Pass_Fitness.Models.Trainers", b =>
                {
                    b.Property<int>("Trainersid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trainersid"));

                    b.Property<DateOnly>("Datehired")
                        .HasColumnType("date");

                    b.Property<int>("Personid")
                        .HasColumnType("int");

                    b.Property<string>("Trainedfield")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Trainersid");

                    b.ToTable("Trainers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
